### ISSUE TITLE
codigo limpio

### ISSUE THREAD

**Issue by JimenaEB** [JuanLGC/Spotify_look_a_like_player#3]
Tabula bien, no uses una ternaria y el texto del error metelo en un etiqueta html 
https://github.com/JuanLGC/Spotify_look_a_like_player/blob/63f55d3b2952077f25a3e19bedef4d1f94f93036/src/js/component/songList.js#L24

**Comment by JuanLGC** [comment]
La tabulacion no la pude corregir toda ya que el mismo boilerplate cuando guardas hace sus tabulaciones.
